backend:
  name: github
  repo: JenuTandel/Docusaurus
  branch: main # Adjust this if using a different branch

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog" # Ensure this is correct
    create: true
    format: "frontmatter"
    slug: "{{slug}}" # Use slug as the filename identifier
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - label: "Authors"
        name: "authors"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image_url", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "docs"
    label: "Docs"
    folder: "docs"
    format: "frontmatter"
    identifier_field: "title"
    nested:
      depth: 5
    create: true
    slug: "{{fields.title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Description", name: "description", required: false }
      - { label: "Tags", name: "tags", required: false }
      - label: "Table"
        name: "table"
        widget: "list"
        required: false
        fields:
          - { label: "Logo", name: "col1", widget: "string", required: false }
          - { label: "Name", name: "col2", widget: "string", required: false }
          - {
              label: "Description",
              name: "col3",
              widget: "string",
              required: false,
            }
      - { label: "Body", name: "body", widget: "markdown" }
