backend:
  name: git-gateway
  branch: main # Change to your actual branch

media_folder: "static/img"
public_folder: "/img"

local_backend: true

collections:
  - name: "docs"
    label: "Documentation"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
